/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppRouteImport } from './routes/app'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as TrackShortIdRouteImport } from './routes/track.$shortId'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppProductsIndexRouteImport } from './routes/app.products.index'
import { Route as AppOrdersIndexRouteImport } from './routes/app.orders.index'
import { Route as AppProductsNewRouteImport } from './routes/app.products.new'
import { Route as AppProductsImportRouteImport } from './routes/app.products.import'
import { Route as AppProductsProductIdRouteImport } from './routes/app.products.$productId'
import { Route as AppOrdersShortIdRouteImport } from './routes/app.orders.$shortId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const TrackShortIdRoute = TrackShortIdRouteImport.update({
  id: '/track/$shortId',
  path: '/track/$shortId',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsIndexRoute = AppProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersIndexRoute = AppOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsNewRoute = AppProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsImportRoute = AppProductsImportRouteImport.update({
  id: '/products/import',
  path: '/products/import',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsProductIdRoute = AppProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersShortIdRoute = AppOrdersShortIdRouteImport.update({
  id: '/orders/$shortId',
  path: '/orders/$shortId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/app/settings': typeof AppSettingsRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/track/$shortId': typeof TrackShortIdRoute
  '/app/': typeof AppIndexRoute
  '/app/orders/$shortId': typeof AppOrdersShortIdRoute
  '/app/products/$productId': typeof AppProductsProductIdRoute
  '/app/products/import': typeof AppProductsImportRoute
  '/app/products/new': typeof AppProductsNewRoute
  '/app/orders/': typeof AppOrdersIndexRoute
  '/app/products/': typeof AppProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/app/settings': typeof AppSettingsRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/track/$shortId': typeof TrackShortIdRoute
  '/app': typeof AppIndexRoute
  '/app/orders/$shortId': typeof AppOrdersShortIdRoute
  '/app/products/$productId': typeof AppProductsProductIdRoute
  '/app/products/import': typeof AppProductsImportRoute
  '/app/products/new': typeof AppProductsNewRoute
  '/app/orders': typeof AppOrdersIndexRoute
  '/app/products': typeof AppProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/app/settings': typeof AppSettingsRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/track/$shortId': typeof TrackShortIdRoute
  '/app/': typeof AppIndexRoute
  '/app/orders/$shortId': typeof AppOrdersShortIdRoute
  '/app/products/$productId': typeof AppProductsProductIdRoute
  '/app/products/import': typeof AppProductsImportRoute
  '/app/products/new': typeof AppProductsNewRoute
  '/app/orders/': typeof AppOrdersIndexRoute
  '/app/products/': typeof AppProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/app'
    | '/onboarding'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/app/settings'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/track/$shortId'
    | '/app/'
    | '/app/orders/$shortId'
    | '/app/products/$productId'
    | '/app/products/import'
    | '/app/products/new'
    | '/app/orders/'
    | '/app/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/onboarding'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/app/settings'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/track/$shortId'
    | '/app'
    | '/app/orders/$shortId'
    | '/app/products/$productId'
    | '/app/products/import'
    | '/app/products/new'
    | '/app/orders'
    | '/app/products'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/app'
    | '/onboarding'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/app/settings'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/track/$shortId'
    | '/app/'
    | '/app/orders/$shortId'
    | '/app/products/$productId'
    | '/app/products/import'
    | '/app/products/new'
    | '/app/orders/'
    | '/app/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
  TrackShortIdRoute: typeof TrackShortIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/track/$shortId': {
      id: '/track/$shortId'
      path: '/track/$shortId'
      fullPath: '/track/$shortId'
      preLoaderRoute: typeof TrackShortIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/products/': {
      id: '/app/products/'
      path: '/products'
      fullPath: '/app/products/'
      preLoaderRoute: typeof AppProductsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/orders/': {
      id: '/app/orders/'
      path: '/orders'
      fullPath: '/app/orders/'
      preLoaderRoute: typeof AppOrdersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/products/new': {
      id: '/app/products/new'
      path: '/products/new'
      fullPath: '/app/products/new'
      preLoaderRoute: typeof AppProductsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/products/import': {
      id: '/app/products/import'
      path: '/products/import'
      fullPath: '/app/products/import'
      preLoaderRoute: typeof AppProductsImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/products/$productId': {
      id: '/app/products/$productId'
      path: '/products/$productId'
      fullPath: '/app/products/$productId'
      preLoaderRoute: typeof AppProductsProductIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/orders/$shortId': {
      id: '/app/orders/$shortId'
      path: '/orders/$shortId'
      fullPath: '/app/orders/$shortId'
      preLoaderRoute: typeof AppOrdersShortIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppOrdersShortIdRoute: typeof AppOrdersShortIdRoute
  AppProductsProductIdRoute: typeof AppProductsProductIdRoute
  AppProductsImportRoute: typeof AppProductsImportRoute
  AppProductsNewRoute: typeof AppProductsNewRoute
  AppOrdersIndexRoute: typeof AppOrdersIndexRoute
  AppProductsIndexRoute: typeof AppProductsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppOrdersShortIdRoute: AppOrdersShortIdRoute,
  AppProductsProductIdRoute: AppProductsProductIdRoute,
  AppProductsImportRoute: AppProductsImportRoute,
  AppProductsNewRoute: AppProductsNewRoute,
  AppOrdersIndexRoute: AppOrdersIndexRoute,
  AppProductsIndexRoute: AppProductsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
  TrackShortIdRoute: TrackShortIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
